application: eedemo
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: app.app

libraries:
- name: pycrypto
  version: "latest"   
- name: jinja2
  version: "latest"  